### ISSUE TITLE
Maximum number of soldiers/specialists should be 8, not 12

### ISSUE THREAD

**Issue by pfaocle** [BSData/stargrave#2]
From the rulebook:

pg. 23:
> ...recruit up to 8 soldiers to join their crew, of which a maximum of 4 can be specialists.

pg. 27:
> While independent crews are limited to ten permanent members (1 caption, 1 first mate and 8 soldiers)...

Right now a crew with 8 soldiers _and_ 4 specialists can be created, for a total of 14 members if you include Captain and First Mate. It should be **8 soldiers maximum**, of which 4 can be specialists (for a total of 10 members including Caption and First Mate). I've had a look in the Data Editor, but I'm afraid I'm not familiar enough yet to know how to implement this with the constraints.

Other caveats re: the rules - I couldn't find reference to increasing crew size, but I'm pretty new to the game! Also, I have not really considered/read into how Temporary Crewmembers work.

**Comment by ericgibert** [comment]
you are right, at the beginning it is 8 of which 4. Not so sure how to code this. But then I have also seen that here is a power to add a Robot... 
There is also the campaign offering the possibility to add new power, which I limit to 5 currently. But then we can add a Power and save even if there is an error: it is not blocking, just a warning.

**Comment by ericgibert** [comment]
I found at page 97:
NEW SOLDIERS
Players may hire new soldiers for the price listed on the Soldier Tables in Assembling a
Crew (see pages 24 and 25). They may hire as many soldiers as they can afford, up to their
maximum warband size, but are still limited to 4 specialists.

**Comment by ericgibert** [comment]
so limit to specialist to 4 holds while adding soldiers seems possible.
