### ISSUE TITLE
[Anon] Bug report: Standard Crew.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/stargrave#4]
**File:** Standard Crew.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Pathfinder specialists are given heavy armour on export, despite loadout having light armour in app.

**Comment by tilteffect** [comment]
I believe this was fixed in v1.2.1. Please re-open if your issue is different to the one fixed there.
