### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by tilteffect** [BSData/stargrave#7]
### Your Discord

TilteffecT

### Additional information

Hello,

After raising issue #6 I've decided to go ahead and implement the backgrounds, powers and new soldiers from Quarantine 37.

If you would prefer, I can fork the stargrave data and post it to my own repo for you to see, but I would like to add it in myself if possible.

Thanks

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/2209239368)
:robot: Invited @tilteffect with **push** access. Invite can be accepted on https://github.com/BSData/stargrave/invitations
